nightscout:
  image: dhermanns/rpi-nightscout
  environment:
    MONGO_CONNECTION: mongodb://mongo:27017/nightscout
    API_SECRET: your12characterpasswordhere
    BG_HIGH: 240
    BG_LOW: 60
    BG_TARGET_TOP: 180
    BG_TARGET_BOTTOM: 80
  ports:
    - "1337:1337"
  links:
    - mongo
mongo:
  image: dhermanns/rpi-mongo
  command: "/opt/mongodb/bin/mongod"
